# Generated by Django 5.1.1 on 2024-11-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vorgang",
            name="alter_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vorgang",
            name="anzahl_kinder",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vorgang",
            name="bereich_diskriminierung_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vorgang",
            name="betroffen_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vorgang",
            name="diskriminierungsform",
            field=models.ManyToManyField(
                blank=True, to="fairmieten.diskriminierungsform"
            ),
        ),
        migrations.AddField(
            model_name="vorgang",
            name="gender_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vorgang",
            name="prozeskostenuebernahme_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
