# Generated by Django 5.1.2 on 2024-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0003_rename_sprache_vorgang_sprache_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorgangstyp',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
