# Generated by Django 5.1.1 on 2024-09-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0004_remove_vorgang_diskriminierungsart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("alter_item", models.CharField(max_length=100)),
                ("anzahl_kinder", models.IntegerField(blank=True, null=True)),
                ("gender_item", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="vorgang",
            name="plz",
        ),
        migrations.RemoveField(
            model_name="vorgang",
            name="uhrzeit_vorfall",
        ),
        migrations.AddField(
            model_name="vorgang",
            name="fallnummer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vorgang",
            name="beschreibung",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vorgang",
            name="datum_kontakaufnahme",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vorgang",
            name="datum_vorfall_von",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vorgang",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fairmieten.person",
            ),
        ),
        migrations.CreateModel(
            name="Verursacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("unternehmenstyp_item", models.CharField(max_length=100)),
                ("personentyp_item", models.CharField(max_length=100)),
                (
                    "vorgang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fairmieten.vorgang",
                    ),
                ),
            ],
        ),
    ]
