# Generated by Django 5.1.2 on 2024-11-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0004_alter_vorgangstyp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vorgang",
            name="ander_sprache",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
