# Generated by Django 5.1.1 on 2024-09-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0005_person_remove_vorgang_plz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charts",
            name="name",
        ),
        migrations.RemoveField(
            model_name="charts",
            name="url",
        ),
        migrations.AddField(
            model_name="charts",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charts",
            name="type",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charts",
            name="variable",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
