# Generated by Django 5.1.1 on 2024-09-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0005_person_remove_vorgang_plz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vorgang',
            name='kontakaufnahme_durch_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vorgang',
            name='vorgangstyp_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
