# Generated by Django 5.1.2 on 2024-11-25 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0006_rename_ander_sprache_vorgang_andere_sprache"),
    ]

    operations = [
        migrations.AddField(
            model_name="vorgang",
            name="anderer_bereich_diskriminierung",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vorgang",
            name="datum_kontaktaufnahme",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
