# Generated by Django 5.1.1 on 2024-09-30 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0007_alter_charts_id_alter_diskriminierung_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vorgang',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='vorgang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fairmieten.vorgang'),
        ),
    ]
