# Generated by Django 5.1.2 on 2024-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0007_vorgang_anderer_bereich_diskriminierung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vorgang",
            name="andere_diskriminierungsform",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
