# Generated by Django 5.1.1 on 2024-10-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0007_charts_name"),
        ("fairmieten", "0008_remove_vorgang_person_person_vorgang"),
    ]

    operations = []
