# Generated by Django 5.1.2 on 2024-11-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0008_vorgang_andere_diskriminierungsform"),
    ]

    operations = [
        migrations.AddField(
            model_name="vorgang",
            name="andere_diskriminierung",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
