# Generated by Django 5.1.1 on 2024-10-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0009_merge_20241001_0920"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Charts",
        ),
    ]
