# Generated by Django 5.1.1 on 2024-10-02 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0010_delete_charts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rechtsbereich",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="betroffen_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="prozeskostenuebernahme_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vorgang",
            name="zugang_fachstelle_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vorgang",
            name="rechtsbereich",
            field=models.ManyToManyField(blank=True, to="fairmieten.rechtsbereich"),
        ),
    ]
