# Generated by Django 5.1.2 on 2025-02-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0010_alter_vorgang_fallnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorgang',
            name='fallnummer',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
