# Generated by Django 5.1.1 on 2024-10-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0011_rechtsbereich_person_betroffen_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorgang',
            name='bezirk_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vorgang',
            name='sprache',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
