# Generated by Django 5.1.1 on 2024-10-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0013_formlabels_formvalues_alter_person_vorgang'),
        ('fairmieten', '0014_formlabel_data'),
    ]

    operations = [
    ]
