# Generated by Django 5.1.1 on 2024-10-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0012_rename_vorgang_id_intervention_vorgang_and_more'),
    ]

    operations = [
    ]
