# Generated by Django 5.1.1 on 2024-10-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0015_merge_20241006_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='formvalues',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
