# Generated by Django 5.1.1 on 2024-10-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0015_merge_20241006_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vorgang',
            old_name='datum_kontakaufnahme',
            new_name='datum_kontaktaufnahme',
        ),
        migrations.RenameField(
            model_name='vorgang',
            old_name='kontakaufnahme_durch_item',
            new_name='kontaktaufnahme_durch_item',
        ),
    ]
