# Generated by Django 5.1.2 on 2024-10-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0017_vorgang_created_by'),
    ]

    operations = [
    ]
