# Generated by Django 5.1.2 on 2024-10-18 16:52

from django.db import migrations
from django.contrib.auth.models import User
import os

def create_superuser(apps, schema_editor):
    # Umgebungsvariablen abrufen
    username = os.getenv('ADMIN_USERNAME', 'admin')
    password = os.getenv('ADMIN_PASSWORD', 'adminpassword')
    email = os.getenv('ADMIN_EMAIL', 'admin@example.com')

    # Superuser nur erstellen, wenn er nicht bereits existiert
    print("Search for ", username)
    user = User.objects.filter(username=username)
    print("User: ", user)
    if not user.exists():
        print("Create Superuser")
        User.objects.create_superuser(username=username, email=email, password=password)

class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0017_vorgang_created_by'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
