# Generated by Django 5.1.2 on 2024-10-24 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairmieten', '0018_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vorgang',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vorgang',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
