# Generated by Django 5.1.1 on 2024-10-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0019_vorgang_created_vorgang_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="vorgang",
            name="loesungsansaetze_bemerkung",
            field=models.TextField(blank=True, null=True),
        ),
    ]
