# Generated by Django 5.1.1 on 2024-10-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0020_vorgang_loesungsansaetze_bemerkung"),
    ]

    operations = [
        migrations.AddField(
            model_name="vorgang",
            name="ergebnis_bemerkung",
            field=models.TextField(blank=True, null=True),
        ),
    ]
