# Generated by Django 5.1.1 on 2024-10-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairmieten", "0021_vorgang_ergebnis_bemerkung"),
    ]

    operations = [
        migrations.AddField(
            model_name="formvalues",
            name="encoding",
            field=models.IntegerField(default=1),
        ),
    ]
