# Generated by Django 5.1.1 on 2024-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregation", "0002_charts_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="charts",
            name="x_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
